/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_api_v1_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ingest/csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ingest Csv */
        post: operations["ingest_csv_api_v1_ingest_csv_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ingest/xlsx": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ingest Xlsx */
        post: operations["ingest_xlsx_api_v1_ingest_xlsx_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ingest/pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ingest Pdf */
        post: operations["ingest_pdf_api_v1_ingest_pdf_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ingest/paste": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ingest Paste */
        post: operations["ingest_paste_api_v1_ingest_paste_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ingest/drafts/{draft_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Draft */
        get: operations["get_draft_api_v1_ingest_drafts__draft_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ingest/drafts/{draft_id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm Draft */
        post: operations["confirm_draft_api_v1_ingest_drafts__draft_id__confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/funds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Fund */
        post: operations["create_fund_api_v1_funds_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/funds/{fund_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Fund */
        get: operations["get_fund_api_v1_funds__fund_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/benchmarks/library": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Library */
        get: operations["library_api_v1_benchmarks_library_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/benchmarks/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload */
        post: operations["upload_api_v1_benchmarks_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/benchmarks/{code}/returns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fetch Provider Returns
         * @description Fetch a series from the active BenchmarkProvider (not user uploads).
         */
        get: operations["fetch_provider_returns_api_v1_benchmarks__code__returns_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analyses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Analysis */
        post: operations["create_analysis_api_v1_analyses_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analyses/{analysis_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Analysis */
        get: operations["get_analysis_api_v1_analyses__analysis_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analyses/{analysis_id}/compute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Compute */
        post: operations["compute_api_v1_analyses__analysis_id__compute_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnalysisCreate */
        AnalysisCreate: {
            /**
             * Fund Id
             * Format: uuid
             */
            fund_id: string;
            metrics?: components["schemas"]["MetricSelection"];
            /**
             * Rf Annual
             * @default 0
             */
            rf_annual: number;
            /**
             * Mar Annual
             * @default 0
             */
            mar_annual: number;
            /**
             * Omega Threshold
             * @default 0
             */
            omega_threshold: number;
        };
        /** AnalysisOut */
        AnalysisOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Fund Id
             * Format: uuid
             */
            fund_id: string;
            metrics: components["schemas"]["MetricSelection"];
            /** Rf Annual */
            rf_annual: number;
            /** Mar Annual */
            mar_annual: number;
            /** Omega Threshold */
            omega_threshold: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** AnalysisResult */
        AnalysisResult: {
            /**
             * Analysis Id
             * Format: uuid
             */
            analysis_id: string;
            /** Metrics */
            metrics: {
                [key: string]: components["schemas"]["MetricValue"];
            };
            /**
             * Computed At
             * Format: date-time
             */
            computed_at: string;
            /** Version Hash */
            version_hash: string;
        };
        /** BenchmarkLibrary */
        BenchmarkLibrary: {
            /** Items */
            items: components["schemas"]["BenchmarkLibraryItem"][];
            /** Provider Active */
            provider_active: string;
        };
        /** BenchmarkLibraryItem */
        BenchmarkLibraryItem: {
            /** Code */
            code: string;
            /** Name */
            name: string;
            /** Category */
            category: string;
            /** Provider */
            provider: string;
        };
        /** BenchmarkOut */
        BenchmarkOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Code */
            code: string | null;
            /** Provider */
            provider: string;
            /**
             * Inception
             * Format: date
             */
            inception: string;
            /**
             * Last Observation
             * Format: date
             */
            last_observation: string;
            /** N Observations */
            n_observations: number;
        };
        /**
         * BenchmarkUploadFromIngest
         * @description Promote a confirmed IngestionResult into a Benchmark.
         */
        BenchmarkUploadFromIngest: {
            /** Name */
            name: string;
            /** Code */
            code?: string | null;
            series: components["schemas"]["ReturnSeries"];
        };
        /** Body_ingest_csv_api_v1_ingest_csv_post */
        Body_ingest_csv_api_v1_ingest_csv_post: {
            /** File */
            file: string;
        };
        /** Body_ingest_pdf_api_v1_ingest_pdf_post */
        Body_ingest_pdf_api_v1_ingest_pdf_post: {
            /** File */
            file: string;
        };
        /** Body_ingest_xlsx_api_v1_ingest_xlsx_post */
        Body_ingest_xlsx_api_v1_ingest_xlsx_post: {
            /** File */
            file: string;
        };
        /** CellEdit */
        CellEdit: {
            /**
             * Period
             * Format: date
             */
            period: string;
            /** Value */
            value: number | null;
        };
        /**
         * ExtractedReturns
         * @description Result of an ingest, before user confirmation in the correction UI.
         */
        ExtractedReturns: {
            series: components["schemas"]["ReturnSeries"];
            /** Confidence */
            confidence: number;
            /**
             * Tier Used
             * @enum {integer}
             */
            tier_used: 1 | 2 | 3 | 4;
            /**
             * Detected Scale
             * @enum {string}
             */
            detected_scale: "percent" | "decimal";
            /**
             * Warnings
             * @default []
             */
            warnings: string[];
            /**
             * Raw Table
             * @default []
             */
            raw_table: (string | null)[][];
        };
        /** FundOut */
        FundOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /**
             * Inception
             * Format: date
             */
            inception: string;
            /**
             * Last Observation
             * Format: date
             */
            last_observation: string;
            /** N Observations */
            n_observations: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IngestPasteRequest */
        IngestPasteRequest: {
            /**
             * Name
             * @default fund
             */
            name: string;
            /** Text */
            text: string;
        };
        /**
         * IngestionConfirm
         * @description User-confirmed correction to apply on /confirm.
         *
         *     `scale` is what the *user* says the values are. The server applies it
         *     (decimal stays as-is, percent divides by 100) and persists a Fund.
         */
        IngestionConfirm: {
            /**
             * Scale
             * @enum {string}
             */
            scale: "percent" | "decimal";
            /** Name */
            name?: string | null;
            /** Edits */
            edits?: components["schemas"]["CellEdit"][];
        };
        /**
         * IngestionDraft
         * @description A parsed-but-unconfirmed series — what /ingest/* returns.
         */
        IngestionDraft: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /**
             * Detected Scale
             * @enum {string}
             */
            detected_scale: "percent" | "decimal";
            /**
             * Tier Used
             * @enum {integer}
             */
            tier_used: 1 | 2 | 3 | 4;
            /** Confidence */
            confidence: number;
            /** Confidence Components */
            confidence_components?: {
                [key: string]: number;
            };
            /** Points */
            points: components["schemas"]["ReturnPoint"][];
            /** Warnings */
            warnings?: string[];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** MetricSelection */
        MetricSelection: {
            /** Metric Ids */
            metric_ids?: string[];
        };
        /** MetricValue */
        MetricValue: {
            /** Metric Id */
            metric_id: string;
            /** Value */
            value: number | null;
            /** Formatted */
            formatted: string;
        };
        /** RegisterRequest */
        RegisterRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** ReturnPoint */
        ReturnPoint: {
            /**
             * Period
             * Format: date
             */
            period: string;
            /** Value */
            value: number;
        };
        /** ReturnSeries */
        ReturnSeries: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Points */
            points: components["schemas"]["ReturnPoint"][];
            /**
             * Inception
             * Format: date
             */
            inception: string;
            /**
             * Last Observation
             * Format: date
             */
            last_observation: string;
            /** N Observations */
            n_observations: number;
            /**
             * Source
             * @enum {string}
             */
            source: "csv" | "xlsx" | "pdf_tier1" | "pdf_tier2" | "pdf_tier3" | "paste" | "library";
            /** Checksum */
            checksum: string;
        };
        /** UserOut */
        UserOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: boolean | string;
                    };
                };
            };
        };
    };
    register_api_v1_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                qorba_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingest_csv_api_v1_ingest_csv_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                qorba_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_ingest_csv_api_v1_ingest_csv_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestionDraft"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingest_xlsx_api_v1_ingest_xlsx_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                qorba_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_ingest_xlsx_api_v1_ingest_xlsx_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestionDraft"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingest_pdf_api_v1_ingest_pdf_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                qorba_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_ingest_pdf_api_v1_ingest_pdf_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestionDraft"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingest_paste_api_v1_ingest_paste_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                qorba_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IngestPasteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestionDraft"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_draft_api_v1_ingest_drafts__draft_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                draft_id: string;
            };
            cookie?: {
                qorba_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestionDraft"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_draft_api_v1_ingest_drafts__draft_id__confirm_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                draft_id: string;
            };
            cookie?: {
                qorba_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IngestionConfirm"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FundOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_fund_api_v1_funds_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                qorba_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExtractedReturns"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FundOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_fund_api_v1_funds__fund_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                fund_id: string;
            };
            cookie?: {
                qorba_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FundOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    library_api_v1_benchmarks_library_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                qorba_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BenchmarkLibrary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_api_v1_benchmarks_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                qorba_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BenchmarkUploadFromIngest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BenchmarkOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    fetch_provider_returns_api_v1_benchmarks__code__returns_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: {
                qorba_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_analysis_api_v1_analyses_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                qorba_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalysisCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_analysis_api_v1_analyses__analysis_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                analysis_id: string;
            };
            cookie?: {
                qorba_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compute_api_v1_analyses__analysis_id__compute_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                analysis_id: string;
            };
            cookie?: {
                qorba_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
